application: stretchhog-1001
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


#- url: /music/.*
#  script: music.app
#
- url: /comics/.*
  script: main.app
  login: admin

#- url: /blog/admin/.*
#  script: main.app
#  login: admin
#
#- url: /ai/.*
#  script: ai.app
#
#- url: /fitness/.*
#  script: fitness.app
#
#- url: /admin/.*
#  script: admin.app
#  login: admin

- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/fonts
  static_dir: static/fonts

- url: /static/images
  static_dir: static/images

- url: /.*
  script: main.app

