application: stretchhog-1001
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /comics/.*
  script: main.app
  login: admin

- url: /admin/.*
  script: main.app
  login: admin

- url: /partials
  static_dir: client/partials

- url: /css
  static_dir: client/css

- url: /js
  static_dir: client/js

- url: /dependencies
  static_dir: client/dependencies

- url: /fonts
  static_dir: client/fonts

- url: /images
  static_dir: client/images

- url: /.*
  script: main.app

